Add-Type -AssemblyName System.Speech
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer

$sentences = @(
    "What time is it today",
    "Turn on the living room light",
    "The weather looks cloudy this morning",
    "Please close the door behind you",
    "I need to buy some groceries later",
    "The meeting starts at nine tomorrow",
    "Can you pass me the remote control",
    "She walked quickly down the street",
    "The coffee is getting cold now",
    "We should leave before it rains",
    "He forgot his keys on the table",
    "The train arrives in ten minutes",
    "I am going to the market",
    "The children are playing outside",
    "This restaurant serves great food",
    "My phone battery is almost dead",
    "The movie starts at eight tonight",
    "She is reading a new book",
    "The traffic was heavy this morning",
    "I will call you after lunch",
    "The garden needs some watering",
    "He is learning to play guitar",
    "The library closes at six",
    "We watched the sunset together",
    "The printer is out of paper",
    "She bought a new laptop yesterday",
    "The dog is barking loudly outside",
    "I forgot to lock the car",
    "The bakery smells amazing today",
    "He runs five miles every morning",
    "The internet connection is very slow",
    "They are painting the fence white",
    "The soup needs more salt",
    "I left my umbrella at home",
    "The stars are bright tonight",
    "She sings in the school choir",
    "The bridge was built years ago",
    "He is fixing his bicycle now",
    "The classroom was very quiet",
    "We ordered pizza for dinner",
    "The airport was extremely crowded",
    "She planted flowers in the yard",
    "The clock on the wall stopped",
    "He always arrives early to work",
    "The ocean waves were very calm",
    "I need new shoes for winter",
    "The bakery opens at seven",
    "They are moving to a new house",
    "The music was too loud",
    "She wrote a letter to her friend",
    "The bus was late again today",
    "He enjoys hiking on weekends",
    "The kitchen needs to be cleaned",
    "I saw a rainbow after the storm",
    "The teacher explained the lesson clearly",
    "We planted a tree in the backyard",
    "The store closes early on Sundays",
    "She takes the dog for a walk",
    "The phone rang three times",
    "He forgot his umbrella again",
    "The soup was too spicy",
    "They watched a documentary last night",
    "The car needs an oil change",
    "I organized my desk this morning",
    "The baby fell asleep quickly",
    "She practices piano every evening",
    "The wind is very strong today",
    "He painted the wall light blue",
    "We visited the museum on Saturday",
    "The bread is fresh from the oven",
    "I updated my computer software",
    "The lake freezes in winter",
    "She wore a red jacket today",
    "The plane landed safely on time",
    "He is studying for his exam",
    "The garden is full of butterflies",
    "We cleaned the house together",
    "The soup kitchen needs volunteers",
    "I charged my phone overnight",
    "The mountains looked beautiful today",
    "She is baking cookies for the party",
    "The road was closed for repairs",
    "He collects old vinyl records",
    "The rain stopped after an hour",
    "We are planning a trip soon",
    "The cat is sleeping on the couch",
    "I need to renew my license",
    "The store had a big sale",
    "She is learning a new language",
    "The fireworks lit up the sky",
    "He repaired the broken window",
    "The soup was ready in minutes",
    "We took photos at the beach",
    "The office was empty today",
    "I misplaced my reading glasses",
    "The concert lasted three hours",
    "She jogged around the park twice",
    "The recipe calls for two eggs",
    "He fixed the leaking faucet",
    "The stadium was full of fans",
    "We are almost out of milk"
)

$i = 20
foreach ($sentence in $sentences) {
    $filename = "data\negative\neg_{0:D3}.wav" -f $i
    $synth.SetOutputToWaveFile($filename)
    $synth.Speak($sentence)
    $synth.SetOutputToDefaultAudioDevice()
    Write-Host "Saved $filename : $sentence"
    $i++
}

$synth.Dispose()
Write-Host "`nDone. Generated $($sentences.Count) negative samples."